suryanshsk/Python-Voice-Assistant-Suryanshsk

- main_assistant.py
Fixes Issue #5 
Key Changes:
get_greeting() function:
This function determines the appropriate greeting based on the current hour.
If the hour is before 12 PM, it says "Good morning."
Between 12 PM and 6 PM, it says "Good afternoon."
After 6 PM, it says "Good evening."
if 'time' in query.lower() block:
The assistant greets the user based on the current time using get_greeting().
It then provides the exact time in HH:MM:SS format.
> addition of informing the time feature

- main_assistant.py
Error Handling: Added try-except blocks around speech recognition, Wikipedia search, weather fetching, and more.
Provided user-friendly feedback when operations fail.
Logging: Replaced all print() statements with logging for better debugging and information tracking.
Speech Recognition Timeout: Added a timeout for speech recognition to avoid blocking the main loop indefinitely.
Combined Exit Conditions: Combined 'exit' and 'stop' into one condition to simplify the control flow.
User-Friendly Fallbacks: Provided clear responses when a task like fetching weather, news, or searching Wikipedia fails.
> Changes made in main_assistant.py

- jokes.py
The following features has been added:
1. Category jokes
2. save the favourite jokes
3. save the favourite jokes from the previous visit
4. Clear the previous favourite jokes
5. Delete all the jokes
6. Repeat the last joke
7. Show your favourite ones
8. Exit, if nothing to input
> Added the features

- weather_info.py
Error Handling with try-except: The requests.get() call is wrapped in a try-except block to handle potential exceptions, such as network issues.
Input Validation
API Key Security: The API key is now fetched securely from an environment variable (OPENWEATHER_API_KEY)
> Updated weather_info.py

- Find_a_way.py
1. Offering shortest path
2. Works on constant feedback system
3. Great UI
> Additon of a navigation tool 

- README.md
Structured it to be more readable, include badges for visual appeal, and ensure that it's easy to navigate and understand.
> Improve README format

- frontend/index.html
- frontend/script.js
- frontend/style.css
Issue #38 
done [feature section design is changed]
> Update of Ui of feature section

- news_info.py
Okay, so I added the following things to the code:
1. Dynamic News Fetching:
Utilizes the News API to retrieve the latest articles based on user-defined parameters, such as category and search keywords.
Supports fetching articles from specific categories, including general, business, technology, sports, entertainment, politics, health, and science.
2. News Category, like users can specify the category of news they wish to fetch.
Number of Articles like users can define how many articles they want to retrieve (with validation to ensure positive integers).
Keyword Search: Users can enter a keyword to search for specific articles.
3. JSON Data Handling: The fetched articles are parsed from JSON format, allowing easy access to relevant data fields such as title, author, publication date, and …
> Added new features to the "news" file

- .gitignore
- README.md
-  fixed #48 
To successfully implement the `.gitignore` file, completed the following steps:
Familiarize yourself with the project's directory layout and file types.
Determine which files and directories should be excluded from version control.
Double-check to ensure that only unnecessary files are included in the `.gitignore`.
Implement the finalized entries in the `.gitignore` file.
Create a pull request to merge the changes into the main branch.
> added .gitignore

- frontend/index.html
- frontend/style.css
- index.html
- style.css
#59 
###Before
###After
>>>Improve front-of the web-site to look cool as the name.
> improve front-end to make it good-looking.

- unit_convertor.py
Issue: #53 
I have added a voice-controlled unit conversion feature which is user friendly and easy to use. 
Appropriate error handling is also done.
> Added a unit conversion feature

- Guesser.py
- akinator.py
- song_quiz.py
- trivia_night.py
fix #54 
Successfully able to create these 4 games should function with the correct library.
> Adding a few games like the ones in Alexa.

- README.md
- language_translator.py
Issue: #65 
I have added a voice-controlled translation assistant that:
1)Listens to spoken commands.
2)Extracts the text and target language.
3)Translates the text using the translate-python library.
4)Speaks the translated text using text-to-speech.
4)Keeps running until the user says "exit" or "stop".
> Added a language translation feature

- gemini_info.py
- main_assistant.py
- open_files.py
Fix #77 
Added file opener feature
> Final file opener code

- JARVIS/.gitattributes
- JARVIS/Functions/Run.py
- JARVIS/Functions/Take_command.py
- JARVIS/Functions/application.py
- JARVIS/Functions/greet.py
- JARVIS/Functions/screenshot.py
- JARVIS/Functions/talk.py
- JARVIS/README.md
- JARVIS/main.py
- JARVIS/requirements.txt
---
issue Number #75 
Add voice command recognition to JARVIS to support the following features:
1. **Voice Command Recognition**: Listen to user commands.
2. **Application Opening**: Open apps like Calculator, Notepad via voice.
3. **Web Search**: Perform Google searches using voice commands.
4. **Play Music**: Search and play music from YouTube via voice.
5. **Screenshot Capture**: Take screenshots with a voice command, saving them with a custom name.
6. **Greeting**: JARVIS should greet the user upon activation.
- **SpeechRecognition**: For voice input.
- **os/subprocess**: For opening apps.
- **webbrowser**: For web searches.
- **pytube**: For playing YouTube music.
- **pyautogui**: For capturing screenshots.
---
> Basic Voice Command Features

- gemini_info.py
- main_assistant.py
- open_files.py
Fix #68 
Added custom website openable ability based on query.
> Any website can be opened

- new_weather_info.py
- test_weather.py
Features Added:
1. 5-Day Weather Forecast: Users can now retrieve a 5-day weather forecast for any specific city.
2. Weather Alerts: The system now displays weather alerts for the specified city using geographic coordinates (latitude and longitude).
3. Temperature Units Selection: Users can choose between metric (°C), imperial (°F), and Kelvin units for temperature display.
4. Improved Error Handling: Enhanced error handling provides clear guidance for invalid inputs and API responses, ensuring more robust user interaction.
5. Favorite Cities: Implemented functionality to save and retrieve favorite cities using a JSON file, allowing quick access to weather information.
6. Logging for API Calls and Errors: Introduced logging to track API calls and log errors for debugging and monitoring …
> Added the required features (New Weather file)

- Recipe-book/Recipes.py
- Recipe-book/readme.md
- Storyteller/Readme.md
- Storyteller/Storytime.py
fixes #72 
I have added these files with the necessary libraries required and description about how they function and what the dataflow in the code is like.
> Added the codes for storyteller and recipe book with a readme file

- frontend/index.html
- frontend/style.css
>I made your website responsive. check previous one it is not responsive.
>implement static feature to navbar.
>i  changed 70% of your Css code.
>HTML minor change.
>I made changes in html and css
> Navbarchange

- stocks.py
Fix #80 
Added feature to get stocks data if stock symbol are given as input.
> added stocks capability

- main_assistant.py
Fix #81 
Added headstart options to the assisstant
> Added headstart options

- email_sender.py
- main_assistant.py
Fix #94 
I have added a feature to send emails to a bulk amount of people.
Currently the bot send reminders to receptionists added at the top of the main_assisstant code
> Feature : sending alerts on mail.

- sample.py
- telegram_bot.py
Fix #99 
I have added a feature to talk in telegram with bot.
> Added telegram bot feature.

- real_time_shopping_list.py
I have solved all the syntax errors in the real time shopping codes.
Fixed #102
> bug fixes done in real time shopping code

- new_weather_info.py
- real_time_shopping_list.py
- requirements.txt
- update_req.py
I have added python code to scan all python files and automatically add modules to requirements.txt file.
> Added automatic requirements.txt updater

- auto_update_requirements.py
This PR introduces a script to automate the generation and update of the `requirements.txt` file for the project. The script analyzes the imports in all Python files, filters out standard library modules and custom project-specific modules, and identifies any external packages that are not listed in `requirements.txt`. If any missing packages are found, it installs them and appends them to the `requirements.txt` file.
Additionally, this PR integrates the use of `pipreqs` as an alternative, streamlined solution to automatically generate the `requirements.txt` file based on actual imports within the project files.
- **Imports Analysis**: Scans all Python files in the project to identify the imported modules.
- **Package Installation**: Automatically installs missing packages and adds them …
> [Feature]: Add a python file to update requirements.txt automatically.

- task_automation.py
- test_email.py
1. Email Notifications:Added functionality to send email notifications for task updates using Gmail's SMTP server.
2. Task Management with SQLite:Tasks can now be added, edited, deleted, completed, and searched.
* Task prioritization (low, medium, high) and due dates are supported.
* Database-backed task storage ensures persistent task tracking.
3. Appointment Scheduling:
* Introduced appointment scheduling with reminders using the schedule library.
* Improved Task Display: Tasks are now displayed with status (completed/not), priority, and due date for better clarity.
@suryanshsk issue no. #90
> Added task_automation file

- Debate Buddy/Debate_buddy.py
- Debate Buddy/Readme.md
- Nurturer/Nurture.py
- Nurturer/Readme.md
- README.md
Fixes #93 
Added two new features with a readme explaining functionality and the flow.
these features help in increasing user interaction.
> Added meditation/ breathing exercises and a virtual debate partner

- index.html
- style.css
This update focuses on enhancing the design of your "Voice Assistant" webpage, making it more colorful and visually attractive while ensuring better readability and user experience.
1. HTML Changes
Navigation Bar (<nav> section):
Added a class logo to the title VOICE.py to differentiate it visually from the other navigation items.
Kept the basic structure of navigation links (Home, Features, Contact, About) and added hover effects for better interactivity.
Maintenance Notice (<div class="A"> section):
Updated the notice message with more engaging icons and text: 🚧 NOTICE: THIS SITE IS UNDER MAINTENANCE 🚧.
Centered the message and applied additional padding for a clean layout.
Content Section (<div class="B"> section):
Updated this section with a welcoming message and informative content …
> changed the web page design

- setup.py
This pull request introduces a user-friendly command-line interface (CLI) `setup.py` for the Python Voice Assistant. It includes the following features:
- **Custom Progress Bar**: Displays a visual progress bar during package installation for improved user experience.
- **Loading Animations**: Provides loading animations to indicate ongoing processes, making it clear to users that tasks are in progress.
- **Automated Virtual Environment Creation**: Automatically creates a virtual environment if one does not already exist.
- **Dependency Installation**: Installs required dependencies listed in `requirements.txt` with a streamlined process.
- **Pipreqs Installation**: Installs the `pipreqs` tool for generating and updating `requirements.txt`.
- **Requirements Update**: Automatically updates …
> [Feature] : Automate Dependency Installation and Application Startup 

- sentiment_analysis.py
Fixed #127 
Added sentiment analysis feature.
> Added sentiment analyser tool

- enhanced_weather.py
Fixed #131 
Enhanced weather info with new features such as email alerts
> enhanced weather info with new features.

- qrcodes.py
Fix #130 
Added qrcode generation and scanning features.
> Added qrcode feature

- face_detection.py
> Face detection feature added to the code base

- wikipedia_info.py
Users input their search query, specify the number of sentences for the summary, and choose the language of the Wikipedia page.
Search history
Disambiguation Handling
Language Support
Formatted Output
Users can choose between searching, viewing search history, or exiting the program, enhancing the user experience.
Error handling & logging feature
issue no. #109 
@suryanshsk 
Hey if everything is fine can you please close my issue #90  #70  #109
> added described features in issue (wikipedia file)

- face_detector.py
Added facedetector feature to the assistant.
Fix #137
> Added Face detector to the assisstant

- Interactive Storytelling
Allow the assistant to narrate stories that users can influence by choosing different plot directions or character actions, creating a personalized storytelling experience.
here it has many random stories by which user can enjoy.
> Create Interactive Storytelling

- memory_game.py
A memory game that challenges players to recall sequences of random words from various categories (fruits, clothes, animals, colors, vehicles, food, countries) with adjustable difficulty, hint options, and a leaderboard to track high scores.
fix issue #160 
@suryanshsk
> Added the memory game

- Crisis support/README.md
- Crisis support/crisis_support.py
Issue: #106 
This feature provides crisis support to the user. It can:
1. Recognize Crisis-Related Commands
2. Provide Immediate Support
3. Offer Crisis Helplines
4. Connect to Crisis Resources
> Added a crisis support feature to the voice assistant

- setup.bat
- setup.py
- setup.sh
Addresses Enhancements Over the PR #120 
- Dynamically handles paths for executables (Windows/Unix) to ensure seamless virtual environment setup.
- Suppressed console logs for a more user-friendly setup process.
- Added get_venv_executable() to streamline executable path handling.
- Enhanced setup experience with loading animations and progress bars.
- Improved the overall flow for virtual environment creation, dependency installation, and application execution.
- - Added `setup.sh` for Unix-based systems and `setup.bat` for Windows, streamlining the creation and activation of virtual environments.
> [FIX]: Enhance `setup.py` with Virtual Environment and Cross Platform Support

- Travel buddy/Readme.md
- Travel buddy/Travel_buddy.py
This has a travel planner function embedded which provides locations to visit when user gives an input.
It also has fun facts for certain locations if given user input matches.
> Implemented voice assistive travel partner

- budget_planner.py
I have added budget planner feature.
Fix #140
> Added budget planner

- health.py
I have added health and well ness planner feature.
Fix #142
> Added health and wellness planner

- workout_planner.py
I have added a workout planner feature.
Fix #152
> Added workout planner

- time_module.py
> vs time module

- phone_numbers.py
Fix #192 
This PR adds functionality to parse and validate phone numbers using the phonenumbers library. It retrieves important details like the region code and carrier name, ensuring accurate phone number handling.
Key Features:
Parses and validates international phone numbers.
Extracts region codes and sim card company name information.
Checks if the phone number is valid and possible.
Formats phone numbers in international and national styles.mbers (international_format, national_format)
> Added phone numbers parsing, getting related information codes

- chess.py
Fix #193 
This PR introduces a complete text-based chess game implemented in Python. This chess game will be a part of the assistant's games and entertainment section. The main features include:
Piece Movement: Supports all chess pieces with their respective movement rules.
Basic Validation: Ensures players cannot make invalid moves, including capturing their own pieces.
Turn Management: Alternates turns between players, enforcing proper game flow.
User Interface: Displays the chessboard in the console for easy interaction.
Changes Made:
Implemented movement logic for all pieces (pawns, rooks, knights, bishops, queens, kings).
Added path-clearing checks for non-knight pieces.
Included input validation for player moves.
Enhanced board display for better user experience.
> I have added a chess game in the assistant.

- README.md
Added Table of Contents in the Readme file to enhance navigation and provide a more user-friendly experience for end users.
- Fixes: #195
> Added Table of Contents in README.md file

- Rhythm of Knowledge: Get It Right, Hear It Right!
It plays music for every correct answer.
> Create Rhythm of Knowledge: Get It Right, Hear It Right!

- Voice-Controlled Email and Messaging.py
Created a voice-controlled system for sending and reading emails, messages (SMS, WhatsApp), and social media posts in Python involves using several libraries and APIs.
Closes #203
> Added  Voice-Controlled Email and Messaging.py

- imdb.py
I have added imdb data fetching functions in the bot.
Fix #197
> Added imdb feature

- memorygame.py
I have added memory gui which utilises tkinter and let's the user play.
Fix #199
> Added Memory game

- 20_questions_game.py
1.  Diverse categories for guessing objects.
2.  Three levels affecting guess limits and hints.
3.  Engaging yes/no interaction for gameplay.
4.  Random guessing with tracking of previously guessed objects.
5.  Optional hints based on difficulty.
6.  Players can add new objects to the knowledge base.
7.  Tracks and displays remaining guesses.
8.  Records player scores across rounds.
9.  Allows players to restart or exit the game.
10. Displays the AI's confidence level for each guess.
11. User-friendly console interface for interaction
issue no. #189 
@suryanshsk
> Added the 20 questions game

- Language_Learning_Assistant/Readme.md
- Language_Learning_Assistant/learning.html
- Language_Learning_Assistant/script.js
- Language_Learning_Assistant/style.css
- Voice-Controlled Email and Messaging.py
> Added Language Learning Mode

- Personality_tester/Tester.py
- Personality_tester/readme.md
This helps the user find out their personality type and their special features helping them better understand their talents and traits.
> Added a new personality tester 

- sustainabilty_tracker.py
This program is a sustainability tracker that helps users log and track their environmental impact in areas like transportation, energy usage, water usage, and waste. It saves user data in a JSON file for persistence. Key features:
1. Logging Sustainability Data
2. Carbon Footprint Calculation
3. Sustainability Recommendations
4. Historical Data Tracking
> Added a sustainability tracker

- test_email.py
"enhance(email): add email validation, environment variables, and improved error handling"
Key Enhancements:
Environment Variables:
The email server, port, username, and password are fetched from environment variables for better security.
To set these environment variables in your system or environment, you can run:
Email Validation:
A simple regex pattern is used to check if the recipient email address is valid before attempting to send the email.
MIME Multipart Message:
Instead of a plain string message, we now use MIMEMultipart() to construct the email, making it easier to extend with additional content types like HTML or attachments in the future.
Improved Exception Handling:
Specific exceptions like SMTPAuthenticationError and SMTPConnectError are caught, providing better feedback.
A …
> enhance(email): add email validation, environment variables

- 2048_game.py
fix issue #223 
1. Supports movement in four directions (Up, Left, Down, Right) with automatic merging of matching tiles.
2. Allows undoing the last move.
3. Displays current and high scores, with automatic score saving in JSON file
4. Detects if the player reaches the 2048 tile.
5. Ends the game when no more moves are possible.
6. Adds a new tile (2 or 4) after each move.
7. Displays colored tiles based on their values for better visual representation.
@suryanshsk
> Added the 2048 game

- Detective.py
I have added about 25 cases with relevant syntax ran it locally to check the functionality.
This helps the user sharpen his crime solving skills as a hobby.
> Implemented interactive crime solving game 

- frontend/index.html
#239 
As i show someone mistakenly add extra space (image/  voice.png) between / and voice.png so i just solve this issue.
>>>before.
>>>after.
> front page image(voice.png) not showing issue solved.

- Tutor.py
Closes issue: #228 
This code implements a voice-based tutoring assistant that can help users with math problems, practice languages, and take quizzes on various subjects. It has the following features:
1. User Profile Management
2. Math Tutoring
3. Language Practice
4. Quizzes
> Added a voice assisted tutoring feature

- Time_capsule.py
Fixes #238 
This is a password protected time capsule code which allows the user to store sensitive information to be released after a certain time period.
One can view, search, check and delete but edit(only when the password matched).
> Time capsule code added

- Task-scheduling-via-voice-commands/readme.md
- Task-scheduling-via-voice-commands/task_scheduler.py
This PR introduces a **Task Scheduling and Reminder** feature for the **Cognova** voice assistant, where users can interact with the assistant via voice commands to set tasks or reminders. The system listens for commands such as:
> "Remind me to attend a meeting at 2 PM."
The assistant uses **speech recognition** to capture the user's command, schedules the task using **APScheduler**, and confirms the scheduled task through **text-to-speech**. This provides an intuitive and voice-driven way to manage reminders and daily tasks without needing a keyboard or display interaction.
- **Speech Recognition** to capture voice commands and extract tasks/reminders.
- **Text-to-Speech Response**: The assistant confirms the scheduled task using `pyttsx3` to provide an audio response.
- **Task …
> Add Task Scheduling and Reminder Feature via Voice Commands

- Rock_Paper_Scissors_Game.py
* You can enter the number of games you want to play.
* There is also a score window which is displayed after every turn.
> Rock Paper Scissor added

- text_summarization.py
Use this command to install Hugging Face Transformers library : pip install transformers torch
Fixes #253 
@suryanshsk
> Added text-summarization feature

- mood_tracker.py
1. Mood Logging: Logs mood, notes, gratitude, and positive habits.
2. Daily Quote & Meditation Tip: Provides motivation and meditation advice.
3. Music Suggestions: Recommends playlists based on mood.
4. Mood Trends & Summary: Visualizes mood trends and gives mood summaries.
5. Personalized Recommendations: Suggests activities based on recent mood.
6. Mood Prediction: Predicts mood patterns for each weekday.
7. Reminders: Sends daily meditation and exercise reminders.
fix issue #236 
@suryanshsk
> Added mood tracker

- test_weather.py
Incorrect Coordinates for Weather Alerts: The test for weather alerts uses hard-coded coordinates for Lucknow, which do not correspond to the specified city ("Chennai"). This could lead to inaccurate alert data being tested. The correct coordinates for Chennai are approximately (13.0827, 80.2707).
Missing Unit Parameter in 5-Day Forecast Function: The call to get_weather_forecast(city_name) does not include the unit parameter, which may result in unexpected behavior if the function requires it.
Lack of Error Handling: While some basic error handling exists, it could be improved by adding more specific exceptions for each function call to provide clearer feedback on what might be going wrong during the tests.
Test Assertions Not Fully Implemented: Assertions are present, but additional …
> Enhanced the test_weather.py

- linearEquations.py
Issue #243
This project solves a system of three linear equations using Python's NumPy library and visualizes the solution in 3D using Matplotlib. The user inputs three linear equations, each in the form of ax + by + cz = d. The script:
- Accepts the coefficients for three linear equations.
- Uses NumPy’s linalg.solve() function to compute the solution (intersection point) of the system of equations.
- Visualizes the planes represented by the equations using Matplotlib’s 3D plotting capabilities.
- Plots the planes in different colors and marks the intersection point of the three planes, which represents the solution to the system.
> Add Solver_linear_equations

- rock_paper_scissor_game.py
** Key Features:**
**Dropdown Menu**: The player selects Rock, Paper, or Scissors.
**Random Computer Choice**: The computer makes a random selection.
**Result Feedback**: Immediate feedback is shown whether the player wins, loses, or ties.
This setup makes the game interactive and straightforward, perfect for learning and a bit of fun!
> Feature request #242: Rock-paper-scissor game added with tkinter

- Memory_assistance.py
This project is a memory assistant that can interact with users via voice commands. It provides various functionalities, including reminders, quizzes, tutoring, and language practice, while also storing and retrieving user-specific data.
> Added a Memory assistance feature

- Escape_room/Escape_room.py
- Escape_room/README.md
Fixes #237 
I have managed to successfully implement this feature. This is a level-based game where a user only moves forward once he clears the current level.
> Escape room using riddles 

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/code_enhancement.md
- .github/ISSUE_TEMPLATE/feature_request.md
added different type templates for issues to make it easy for contributors.
> added issues template. fixes #268

- Customized_voice_responses.py
Closes: #277 
The program implements a voice-activated personal assistant. It features customizable personality modes, such as "professional", "casual", "humorous", and "formal", which influence the tone and formality of responses. The assistant adjusts its mood based on the time of day and can recognize voice commands with error handling for common issues like microphone access or speech recognition failures.
> Added a feature that allows customized voice responses

- sun_scan.py
fix #264  
1.UV Index Tracking: Fetch UV data using location coordinates.
2. Skincare Tips: Provide advice based on UV levels.
3. Sun Exposure Logging: Track and log UV exposure.
4. Solar Energy Potential: Assess solar energy based on UV index.
5. Eclipse Data Retrieval: Access NASA's solar eclipse information.
6. Email Alerts: Send notifications for UV index and skincare advice.
7. Vitamin D Exposure Calculation: Calculate necessary sun exposure for Vitamin D.
8. Sunburn Recovery Tips: Offer recovery advice based on exposure.
9. Optimal Outdoor Timing: Suggest best outdoor times based on UV forecasts.
10. UV Trend Visualization: Visualize UV index trends using plots.
@suryanshsk
> Added Sun Scan

- AES encryption.py
> Create AES encryption.py

- Multi-Device Sync in a virtual assistant.py
> Create Multi-Device Sync in a virtual assistant.py

- sudoku.py
> Added sudoku solver

- Email Sender/attachments.py
- Email Sender/link.py
> Add Email-sender

- Gesture Recognition using CNN.py
> Create Gesture Recognition using CNN.py

- Secure data/Private.py
- Secure data/Readme.md
Fixes #291 
This has multiple level security which allows user to safely secure his data.
This also has custom questions decided by the user if the voice recognition fails.
Password protected.
> Added Privacy features

- google_meet_sheadule.py
This script automates Google Meet scheduling by using Google Calendar API, Gemini AI to extract meeting details from user input, and text-to-speech for event confirmation.
> google_meet_sheadule

- Dijkstra/main.py
- Dijkstra/test_main.py
> Added dijkstra

- pages/weather_info_st.py
**Description:**
This pull request adds a new feature to our Streamlit application, introducing a weather information page where users can input their location. After submitting the form, the application fetches and displays the current weather data for the specified location.
**Changes Made:**
**Testing:**
**Notes:**
- Ensure you have the required API key for the weather service, and set it in your environment variables for seamless functionality.
- Users are encouraged to explore the interface and provide feedback for further improvements.
> Add weather information page with user input forma

- MathsSolver/maths_solver.py
- MathsSolver/test_maths_solver.py
fix issue #326 
1. Basic Arithmetic Operations: Perform addition, subtraction, multiplication, and division.
2. Equation Solver: Solve algebraic equations symbolically.
3. Trigonometric Functions: Calculate sine, cosine, and tangent values for given angles.
4. Differentiation and Integration: Differentiate or integrate mathematical expressions.
5. Factorial Calculation: Compute the factorial of a non-negative integer.
6. Fibonacci Sequence Generator: Generate Fibonacci numbers up to a specified count.
7. Matrix Operations: Add, subtract, and multiply matrices.
8. Complex Number Operations: Perform arithmetic operations (addition, subtraction, multiplication, division) on complex numbers.
9. Unit Conversion: Convert between various units (e.g., meters to feet, kilograms to pounds).
10. …
> Added maths solver/assistant

- faq.html
- index.html
- script.js
- style.css
issue solved #183 
I have added some FAQS please look into it.
If any modifications further needed let me know.
Note:- Add all labels added to issue #183  to this PR. So that GSSoC team can easily recognize the commit!
> Added FAQ Section

- frontend/index.html
I have corrected the path of image so that it is visible now
Previous
Current
> solved issue #314

- hand gestures.py
> Create  hand gestures.py

- random_joke_generator.py
this PR Closes: #287 and adds random joke generator
> added random joke generator

- reactiontimer.py
The added game is useful for the following reasons:
- **Improves Reaction Time:** Players can practice and enhance their reflexes, which can be beneficial in various real-life situations, such as sports or driving.
- **Engaging and Fun:** The game's unpredictable nature keeps players entertained, making it a fun way to pass the time or compete with friends.
- **Simple and Accessible:** With minimal instructions and easy-to-understand mechanics, the game is suitable for all ages, encouraging participation from a wide audience.
- **Performance Tracking:** By measuring reaction times, players can track their improvement over multiple rounds, fostering a sense of achievement and motivation to beat personal bests.
- **Cognitive Benefits:** Playing reaction-based games can help improve hand-eye …
> Reaction TImer Game added

- frontend/contact.html
- frontend/index.html
- frontend/style.css
#330 
>>before.
>>After Adding hover property when someone hover onto nav icon . the background color of nav-icon background will change.
> hover option activated in contact section nav-bar.

- Daily_journal.py
Closes: #336 
This project is a voice-controlled journaling assistant that allows users to log daily journal entries using speech recognition. It uses text-to-speech to interact with users and prompts them to reflect on their day at a scheduled time, which can be customized. The system performs sentiment analysis on journal entries to provide feedback on the user's emotional state and stores the entries in a personalized JSON file. It also includes error handling for unrecognized commands and invalid time inputs, ensuring a smooth voice-based journaling experience.
> Added a voice based personal journal feature

- index.html
This pull request introduces a trailing cursor effect to improve user interaction and create a more dynamic interface. The effect follows the user's mouse movement, providing a visually engaging experience that complements the overall design.
#378 
https://github.com/user-attachments/assets/cd0fe7f7-1a28-4844-abe6-6553eea0dc62
> Added a trailing cursor effect for enhanced user interaction

- Location_based_services.py
This project is a location-based voice assistant with features for finding nearby services and setting geofencing alerts. It provides information on nearby services like restaurants, gas stations, hospitals, or ATMs based on user location.
> Added a location-based services feature

- Code_help/Code_helper.py
- Code_help/readme.md
This feature adds a code which activates based on voice prompts which generates a code found from a larger database using API keys.
> Added Code helper

- frontend/index.html
- frontend/style.css
Added chat box which enables users to ask questions
> Solved issue #369

- Python Snippets/qr.py
> added qr-code

- Python Snippets/Algorithms/Astar.py
- Python Snippets/Algorithms/BFS.py
- Python Snippets/Algorithms/Bellman-Ford.py
- Python Snippets/Algorithms/Binary-Search.py
- Python Snippets/Algorithms/DFS.py
- Python Snippets/Algorithms/Dijkstra.py
- Python Snippets/Algorithms/Fibonacci.py
- Python Snippets/Algorithms/Floyd-Warshall.py
- Python Snippets/Algorithms/Kruskal.py
- Python Snippets/Algorithms/Prim.py
- Python Snippets/Algorithms/Warshall.py
> Added 12 algos

- Python Snippets/Sorting-Algorithms/Bitonic-sort.py
- Python Snippets/Sorting-Algorithms/Bubble-sort.py
- Python Snippets/Sorting-Algorithms/Bucket-sort.py
- Python Snippets/Sorting-Algorithms/Comb-sort.py
- Python Snippets/Sorting-Algorithms/Counting-sort.py
- Python Snippets/Sorting-Algorithms/Cycle-sort.py
- Python Snippets/Sorting-Algorithms/Gnome-sort.py
- Python Snippets/Sorting-Algorithms/Heap-sort.py
- Python Snippets/Sorting-Algorithms/Insertion-sort.py
- Python Snippets/Sorting-Algorithms/Jump-sort.py
fixes #408 
Added the following sorting algos :- 
Bitonic Sort
Bubble Sort
Bucket Sort
Comb Sort
Counting Sort
Cycle Sort
Gnome Sort
Heap Sort
Insertion Sort
Jump Sort
> Added 10 sorting algos

- Chat-App/client.py
- Chat-App/server.py
> Added chat-app

- Python Snippets/Sorting-Algorithms/Merge-sort.py
- Python Snippets/Sorting-Algorithms/Pigeonhole-sort.py
- Python Snippets/Sorting-Algorithms/Quick-sort.py
- Python Snippets/Sorting-Algorithms/Radix-sort.py
- Python Snippets/Sorting-Algorithms/Randomized-quick-sort.py
- Python Snippets/Sorting-Algorithms/Selection-sort.py
- Python Snippets/Sorting-Algorithms/Shell-sort.py
- Python Snippets/Sorting-Algorithms/Stooge-sort.py
- Python Snippets/Sorting-Algorithms/Strand-sort.py
- Python Snippets/Sorting-Algorithms/Tree-sort.py
> Added 10 more algos

- frontend/index.html
- frontend/style.css
Used the same trailing cursor effect on the landing page
https://github.com/user-attachments/assets/e342bf39-365c-42a4-a91d-a264b9b5e98d
> Enhancingthe landing page

- contact.css
- contact.html
- faq.html
- index.html
- style.css
i have created a beautiful UI for the home page and changed the CSS of the paged and added the contact us page form
> Updated Landing Page 

- frontend/index.html
- frontend/style.css
> Darkmode togle background removed

- frontend/contact.html
#383 
>>>now after adding footer to the contact section.
> Add footer section to the contact section.

- Personal Finance Tracker/README.md
- Personal Finance Tracker/finance_tracker.py
Closes: #388 
This feature utilizes voice recognition to help users manage their finances. It allows users to log expenses, set budgets, and check remaining budgets using voice commands. Data is stored in a JSON file, enabling persistent tracking of expenses and budgets. The application is designed for easy interaction, making personal finance management accessible and efficient.
> Added a Personal Finance Management feature

- Simple-Python-Algorithms/binary_exponentiation.py
- Simple-Python-Algorithms/exponentiation_by_squaring.py
- Simple-Python-Algorithms/flood_fill.py
- Simple-Python-Algorithms/gcd.py
- Simple-Python-Algorithms/kadane.py
- Simple-Python-Algorithms/lcm.py
- Simple-Python-Algorithms/longest_common_subsequence.py
- Simple-Python-Algorithms/sieve_of_eratosthenes.py
- Simple-Python-Algorithms/sliding_window.py
- Simple-Python-Algorithms/two_pointer.py
Implemented algorithms for GCD, LCM, Sieve of Eratosthenes, Exponentiation by Squaring, Binary Exponentiation, Flood Fill, Two Pointer Technique, Sliding Window, Kadane's Algorithm, and Longest Common Subsequence, all with user input support.
> 10 simple python algorithms Solutions 

- emotional_charades.py
issue fix #390 
Features of Emotional Charades
1. Engaging Gameplay: Players act out emotions based on randomly assigned clues.
2. Difficulty Levels: Options to select from Easy, Medium, and Hard for tailored challenges.
3. Input Timeout: 10-second time limit for guesses, adding excitement and urgency.
4. Hints Available: Players can request hints for assistance during the game.
5. Score Tracking: Points awarded based on difficulty level and correct guesses.
6. Game Summary: Displays total guesses, correct guesses, and final score.
7. Performance Feedback: Provides users with a performance percentage and motivational feedback after the game.
@suryanshsk
> Added the emotional charades games

- Book_Recommadation_System/README.md
Issue no - #432 
i have added entire folder including all mandatory files.
@suryanshsk is there any confilcts let me know !
> Book Recommendation System

- Investment Tracking/README.md
- Investment Tracking/investment_tracker.py
This feature is a Python-based application that allows users to manage their investments through voice commands. Utilizing text-to-speech and speech recognition, it enables functionalities such as logging investments, setting price alerts, checking portfolio summaries, and retrieving total portfolio value.
> Added an investment tracking feature

- Connect/Chat.py
- Connect/README.md
Fixes #443 
This feature allows the user to communicate with any other user with just their username after authentication.
- Dynamic functionality 
- Real time audio capture 
Are few of the features that make it more user friendly and reliable
> Implemented voice communication feature

- TTS(TEXT TO SPEECH).py
> Create TTS(TEXT TO SPEECH).py

- Book_Recommadation_System/README.md
**Description:**
This pull request updates the README to improve its structure and readability, adding clear sections for project objectives, dataset descriptions, technologies used, and instructions for getting started. Additionally, I've included visual emojis to make it more engaging and easier to navigate.
**Changes Made:**
- Added detailed project objective and methods used.
- Included a summary of the dataset files with descriptions.
- Outlined the repository structure with icons for easier access.
- Suggested potential future enhancements to encourage further contributions.
Please review and merge if everything looks good! @suryanshsk 
fixes: #477
> BOOK RECOMMENDATION PROJECT - Enhanced README 

- Symptom Checker/README.md
- Symptom Checker/symptom_checker.py
Closes: #473 
This feature helps users describe symptoms to receive health advice, set medication reminders, and get alerts when it's time to take medications. It leverages speech recognition to understand user commands and provides responses via text-to-speech (TTS). The system also stores medication reminders and continuously checks for upcoming medications to notify users at the scheduled time.
> Added a symptom checking feature

- Debate Buddy/Debate_buddy.py
- Debate Buddy/Readme.md
- Python Snippets/phone_numbers.py
fix issue #476 
Added Core Enhancements:
1. Implemented timed argument responses to improve structure and conciseness.
2. Real-time feedback for user arguments based on length and content quality.
3. Counter-questioning feature to challenge user arguments and prompt deeper thinking.
4. Scoring system for tracking user and bot performance, with points for each effective response.
5. Session Summary to recap main points, performance scores, and suggestions.
Expected Outcome:
1. Users will receive immediate, constructive feedback after each argument, helping them improve debating skills.
2. Timed responses and counter-questions add realism and encourage users to articulate their points quickly.
3. Final summary will provide a structured recap of user performance and improvement areas. …
> Added the enhanced features to the Debate buddy

- Python Snippets/qrcodes.py
issue fix #498 
1. Intuitive GUI: A user-friendly interface built with Tkinter that allows easy input of data for QR code generation.
2. Multiple Format Options: Users can now generate QR codes in various formats, including PNG, JPEG, and SVG, to suit their needs.
3. QR Code Scanning: Users can upload images containing QR codes for decoding, providing instant access to the embedded data.
4. Data Validation: The application validates input data to ensure only proper URLs or text are processed, improving reliability.
5. History Management: A feature that tracks and displays the history of generated and scanned QR codes, allowing users to review previous entries easily.
When users interact with the application:
1. They will be able to enter data, choose a format, and generate a QR code that …
> Implement Multi-Format Support and Scanning Functionality

- Event_planner/Event.py
- Event_planner/README.md
Fixes #499 
This feature allows the user to plane events for a set date and time based on his schedule. Adding changes and what to do becomes very easy. Added this feature to increase the diversity and functionality domain of this project.
> Added voice-based event planner

- python personal_assistant.py
> Create python personal_assistant.py

- frontend/contact.html
- frontend/index.html
the logo redirection in contact page from contact page to home (main) page is fixed you can check it 
thank you for asssigned it to me.
> logo redirection fixed

- reactiontimer.py
issue closes #539 
Features that i have added:
1. High Score Tracker – Tracks the best reaction time during each session and displays it on the interface.
2. Reaction Time History – Shows the last five recorded reaction times, allowing players to view recent performance.
3. Difficulty Levels – Introduces three difficulty levels (Easy, Medium, Hard), which control the delay before the button turns green.
4. Random Button Position – Randomly repositions the button each round, increasing the game’s challenge.
5. Performance Feedback System – Provides instant feedback based on the player's reaction time, with categories like "Excellent," "Good," or "Try Again!" to encourage improvement.
@suryanshsk
> Enhanced Reaction Timer Game with High Score and Difficulty Levels

- frontend/contact.html
> contact page footer updated
